name: flutter_drawing_app_sample
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  dxf: ^3.1.3
  web: ^0.5.1
  flutter:
    sdk: flutter
  url_launcher: ^6.3.0
  file_saver: ^0.2.13
  permission_handler: ^11.3.1
  flutter_mailer: ^2.1.2
  path: ^1.9.0
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
